apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-persistence-lib
  description: Librería de persistencia
spec:
  type: library
  lifecycle: experimental
  owner: arquitectura-empresarial-team
  system: arquitectura-empresarial
